### ISSUE TITLE
ansible-builder is slow/sometime fail due to pip depsolver

### ISSUE THREAD

**Issue by grimlokason** [ansible/ansible-builder#425] opened 2022-10-20 08:48 UTC
Hello,

Is it possible to add the possibility to use a constraint file to avoid the check of outdated python package ?

In my case : 
- lot of time lost due to PyJWT boto3 and botocore backtracking dependencies 
- faillure because it want to install openshift==0.13.0 while there is a 0.13.1 available ( CF : https://github.com/openshift/openshift-restclient-python/issues/425 )

Best regards !

**Comment by wiad** [comment] 2022-10-21 15:12
I am also hitting the error caused by ansible-builder downloading openshift==0.13.0

**Comment by Akasurde** [comment] 2022-11-01 12:49
@grimlokason @wiad You can use `requirements.txt` to specify the constraints.

**Comment by wiad** [comment] 2022-11-01 19:49
@Akasurde when i try this (`openshift!=0.13.0`) I get rid of the error but the ansible-builder command takes forever to complete because of pip backtracking dependencies (not just of the openshift package but for almost every package). After almost 5 hours I gave up and aborted the build.

**Comment by grimlokason** [comment] 2022-11-02 09:42
> You can use `requirements.txt` to specify the constraints.

Hello, @Akasurde 

Every package within the requirements.txt is going to be installed, thats not what the constraints option of pip is doing.

**Comment by MallocArray** [comment] 2023-04-12 16:06
I was able to speed up my builds by adding a minimum version to each item in the file
```
ucsmsdk>=0.9.14
pywinrm>=0.4.3
```

**Comment by grimlokason** [comment] 2024-01-25 15:14
> I was able to speed up my builds by adding a minimum version to each item in the file
> 
> ```
> ucsmsdk>=0.9.14
> pywinrm>=0.4.3
> ```

Hello,
And how do you do when the package that is leading to the issue is not in your requirement file but is a dependencies ? 
It's quite annoying in my point of view to have to add a dependencies in the requierement :/

**Comment by MallocArray** [comment] 2024-01-25 15:21
> And how do you do when the package that is leading to the issue is not in your requirement file but is a dependencies ?

I ended up just doing `pip3 list` after a successful build to show all installed packages and then added whatever they are currently running as the minimum to requirements.txt

**Comment by Shrews** [comment] 2024-06-27 14:32
With the newly released version `3.1.0` version of `ansible-builder`, you can now exclude any top-level dependencies from collections that may be causing you any issues (see the new `exclude` keyword under [dependencies](https://ansible.readthedocs.io/projects/builder/en/3.1.0/definition/#dependencies)). After excluding, you can then selectively re-add them to the user requirements.txt, if you wish.

Not sure there is much more we can do with this issue, so I'm going to go ahead and close it.

**Closed as completed by Shrews** 2024-06-27 14:32 UTC
