### ISSUE TITLE
Build caching regression

### ISSUE THREAD

**Issue by shanemcd** [ansible/ansible-builder#69] opened 2020-08-06 14:10 UTC
Subsequent runs of `ansible-builder` should be near-instant when inputs dont change. I believed this regressed in https://github.com/ansible/ansible-builder/pull/57. Since we're always re-writing `context/requirements.txt`, this causes the pip install steps to always be run, even when the contents of `requirements.txt` doesn't change.

**Comment by AlanCoding** [comment] 2020-08-11 02:56
It looks like I'm not able to reproduce this, I put up test at #73. Do you think that using podman vs. docker will make a difference?

**Comment by AlanCoding** [comment] 2020-08-11 14:57
After I got some better test information, it turns out this _is_ happening specific to podman.

**Comment by AlanCoding** [comment] 2020-08-13 01:54
Link https://github.com/containers/buildah/pull/2539

The specific problem here might be resolved with #73, but I wouldn't trust that until we change to a different base image and have another round going at the testing.

**Comment by AlanCoding** [comment] 2020-08-26 00:05
@kdelee test coverage in

https://github.com/ansible/ansible-builder/blob/6d6ba5d5934d84d546300f31cfe6048a78555574/test/integration/test_build.py#L113

**Closed as completed** 2020-09-29 19:46 UTC
Labels: bug
