### ISSUE TITLE
Error when building an EE with no / empty requirements.yml

### ISSUE THREAD

**Issue by shanemcd** [ansible/ansible-builder#290] opened 2021-09-28 16:14 UTC
@benthomasson ran into this error when using ansible-builder with an empty `requirements.yml`:

```
Error: error building at STEP "COPY --from=galaxy /usr/share/ansible /usr/share/ansible": error adding sources [/home/ben/.local/share/containers/storage/overlay/7083e897c32eb6c6313cb9c4f92c7ae6ab3500640f7b252f78fadc75bcf3b701/merged/usr/share/ansible]: error checking on source /home/ben/.local/share/containers/storage/overlay/7083e897c32eb6c6313cb9c4f92c7ae6ab3500640f7b252f78fadc75bcf3b701/merged/usr/share/ansible under "/home/ben/.local/share/containers/storage/overlay/7083e897c32eb6c6313cb9c4f92c7ae6ab3500640f7b252f78fadc75bcf3b701/merged": copier: stat: "/usr/share/ansible": no such file or directory
```

**Comment by benthomasson** [comment] 2021-09-28 16:15
requirements.yml:

```
---
collections: []
...
```

**Comment by benthomasson** [comment] 2021-09-28 16:17
It fails in a different way with a proper error message with an empty requirements.yml

```
STEP 6: RUN ansible-galaxy role install -r requirements.yml --roles-path /usr/share/ansible/roles
[WARNING]: You are running the development version of Ansible. You should only
run Ansible from "devel" if you are modifying the Ansible engine, or trying out
features under development. This is a rapidly changing source of code and can
become unstable at any point.
ERROR! No requirements found in file '/build/requirements.yml'
STEP 7: FROM quay.io/ansible/ansible-builder:latest AS builder
Error: error building at STEP "RUN ansible-galaxy role install -r requirements.yml --roles-path /usr/share/ansible/roles": error while running runtime: exit status 1
```

**Comment by Akasurde** [comment] 2023-05-17 18:17
With Ansible Builder v3, I am not able to reproduce this error. 

```yaml
---
collections: []
```

```yaml
---
version: 3

images:
  base_image:
    name: registry.redhat.io/ansible-automation-platform-23/ee-minimal-rhel8:latest

dependencies:
    ansible_core:
        package_pip: ansible-core==2.15.0
    ansible_runner:
        package_pip: ansible-runner==2.3.2
    galaxy: requirements.yml

additional_build_files:
    - src: files/ansible.cfg
      dest: configs

additional_build_steps:
    prepend_final:
        - COPY _build/configs/ansible.cfg /etc/ansible/ansible.cfg

options:
    package_manager_path: /usr/bin/microdnf
```

Closing this now. Please feel free to open a new issue if the problem persists. Thanks.

**Closed as completed by Akasurde** 2023-05-17 18:17 UTC
