### ISSUE TITLE
Allow specifying secrets to download collections from custom locations

### ISSUE THREAD

**Issue by ghost** [ansible/ansible-builder#196] opened 2021-03-29 05:41 UTC
A general use case here would be to download collections from a private git repository, there should be a way to specify a token/key to be mounted onto the container for this purpose

**Comment by JustInVTime** [comment] 2021-04-28 14:05
:+1:

**Comment by AlanCoding** [comment] 2021-05-27 18:10
Going to close as duplicate of https://github.com/ansible/ansible-builder/issues/195

If there's any specific means of passing secrets, please contribute to the discussion there. Thanks.

**Closed as completed by AlanCoding** 2021-05-27 18:10 UTC
Labels: enhancement
