### ISSUE TITLE
Certain python libraries not being installed

### ISSUE THREAD

**Issue by dzeediscoveryzone** [ansible/ansible-builder#429] opened 2022-11-10 19:18 UTC
Hi All,

I've run into an odd issue when building new execution environments. We have a set of AAP templates that require the purestorage library and even though I have it in my requirements file **and** I see it populated correctly in the build context it does not actually get installed into the container image (which completes successfully).

Below is a snipper of the requirements file:
```text
purestorage==1.19.0
py-pure-client==1.20.1
```

In the `_build/requirements.txt` file I also see the exact libraries and versions, however when I shell into the container and try to find it, I don't see it:

![ansible-builder-issue](https://user-images.githubusercontent.com/88047399/201186055-f555eddd-3204-4c04-9dc2-e5d4d3566eb9.png)

When in the container if I manually install purestorage version 1.19.0 (latest) I can interact with the libary properly:

![ansible-builder-issue-2](https://user-images.githubusercontent.com/88047399/201186426-146a3c7e-9beb-4b5e-9dbf-149366ea6057.png)

For a sanity check, I looked at pip after installing it in the container:

![ansible-builder-issue-3](https://user-images.githubusercontent.com/88047399/201186580-c20ad48d-0aa0-420c-88db-22d7f151e035.png)

**Comment by Shrews** [comment] 2022-11-15 14:07
Hi. Could help us reproduce this issue by providing the following:

- The version of `ansible-builder` that you are using.
- Complete output from your run of `ansible-builder` using the `-v 3` option for more verbose output.
- A simplified project (execution-environment.yml, requirements.txt, etc) that we may use that reproduces the issue.

Thanks.

**Comment by dzeediscoveryzone** [comment] 2022-11-15 18:27
> Hi. Could help us reproduce this issue by providing the following:
> 
> * The version of `ansible-builder` that you are using.
`1.2.0`
> * Complete output from your run of `ansible-builder` using the `-v 3` option for more verbose output.
```sh
Ansible Builder is building your execution environment image. Tags: {{ REDACTED }}/ansible-automation-platform/22/ee-vmware-pure:0.1.0
File context/_build/requirements.yml is already up-to-date.
File context/_build/requirements.txt is already up-to-date.
File context/_build/bindep.txt is already up-to-date.
Rewriting Containerfile to capture collection requirements
Running command:
  docker build -f context/Dockerfile -t {{ REDACTED }}/ansible-automation-platform/22/ee-vmware-pure:0.1.0 context
#1 [internal] load build definition from Dockerfile
#1 sha256:b5d168d9509409a10c3dd822536f13d11356c057dd0a0806c1fb863dfb475bf3
#1 transferring dockerfile: 1.38kB 0.0s done
#1 DONE 0.1s

#2 [internal] load .dockerignore
#2 sha256:0615013f5a901e7ee92c9eb33bf2f504ea154940f6d2c9000760c072e22f5010
#2 transferring context: 2B done
#2 DONE 0.1s

#4 [internal] load metadata for {{ REDACTED }}/ansible-automation-platform/22/ansible-builder:latest
#4 sha256:216cc3c9d32922a2d001377a3ec4631943ee1046f4246b77799a1763393f4b25
#4 ...

#3 [internal] load metadata for {{ REDACTED }}/ansible-automation-platform/22/ee-minimal-rhel8:1.0.0-188
#3 sha256:41c07a2500873bae9330727c45ddaed34baaed14559499cba80ca69b9bff2421
#3 DONE 1.2s

#4 [internal] load metadata for  {{ REDACTED }}/ansible-automation-platform/22/ansible-builder:latest
#4 sha256:216cc3c9d32922a2d001377a3ec4631943ee1046f4246b77799a1763393f4b25
#4 DONE 1.4s

#13 [builder 1/6] FROM  {{ REDACTED }}/ansible-automation-platform/22/ansible-builder:latest@sha256:bd838468b579574369b587405e136334af5161015fd8f307aae182a6223a44ac
#13 sha256:87f2974cebc1cd00e9ba6ce25d4bc39b6ca4bdff8031c5c5ea17ed5786a6f205
#13 DONE 0.0s

#5 [galaxy 1/5] FROM  {{ REDACTED }}/ansible-automation-platform/22/ee-minimal-rhel8:1.0.0-188@sha256:4b069982be4fac13286cf332de1aeb32b59aefb30d7d8071f3e5fe73a29286f3
#5 sha256:0bade704c6eafcf4ff01a8730ae2d43f2c6cb21ce6700d85298ade15fc37fdb8
#5 DONE 0.0s

#7 [internal] load build context
#7 sha256:04a539275ec040c698b8b0b9ad096d57fdbc7ec0eebaea83b5e9bc130194e834
#7 transferring context: 150B done
#7 DONE 0.0s

#8 [galaxy 2/5] ADD _build /build
#8 sha256:538a600e0d92b2c49efb9d91900c6ae380da0c84ae5c43ff3282de28f9887e5d
#8 CACHED

#6 [stage-2 2/6] RUN python3 -m pip install --upgrade pip
#6 sha256:3b34d481e14e70be6d279f4b52938fcac74f8c33de589d04230430ca5b618f21
#6 CACHED

#18 [builder 6/6] RUN assemble
#18 sha256:a3b1b96fcd06b501a37b29cc6c38dbed77224e4fa36c3b6d08725113d1a62d2e
#18 CACHED

#14 [builder 2/6] COPY --from=galaxy /usr/share/ansible /usr/share/ansible
#14 sha256:bad494e23e12a308858e3ce0ee7d90008ef42ad14c3079c7596a979de7e5f023
#14 CACHED

#20 [stage-2 5/6] RUN /output/install-from-bindep && rm -rf /output/wheels
#20 sha256:4f7dfddda65125db889ca04179198fb409e7af1ddf238ad49c080e414b8e64cd
#20 CACHED

#17 [builder 5/6] RUN ansible-builder introspect --sanitize --user-pip=requirements.txt --user-bindep=bindep.txt --write-bindep=/tmp/src/bindep.txt --write-pip=/tmp/src/requirements.txt
#17 sha256:c81369556e65a91caad303c4929f60abe3bac7f38a567238d85d14c18d90eb8d
#17 CACHED

#12 [stage-2 3/6] COPY --from=galaxy /usr/share/ansible /usr/share/ansible
#12 sha256:e8f5e5d9543d465a83338fab7ce032bb91cf1cc96e87042c2cf1c3adaf263ae0
#12 CACHED

#15 [builder 3/6] ADD _build/requirements.txt requirements.txt
#15 sha256:f8c3686340eb90d1ffebf454b9bd3562b5951ba86982f6fe78506463dccf7276
#15 CACHED

#11 [galaxy 5/5] RUN ANSIBLE_GALAXY_DISABLE_GPG_VERIFY=1 ansible-galaxy collection install  -r requirements.yml --collections-path "/usr/share/ansible/collections"
#11 sha256:64dab640c9e3e4e564fc7e65c8959f06242fddbb6c4a2f6344f9c514e28a5b03
#11 CACHED

#19 [stage-2 4/6] COPY --from=builder /output/ /output/
#19 sha256:f6460da0c36c087cc83814a652743bb7eeeaa4255c6c89fb5743da491db69674
#19 CACHED

#9 [galaxy 3/5] WORKDIR /build
#9 sha256:cc5ad4566c98d33aad096b938c0a9e502571590dbfb0fa16a7d3f8c349b93960
#9 CACHED

#10 [galaxy 4/5] RUN ansible-galaxy role install  -r requirements.yml --roles-path "/usr/share/ansible/roles"
#10 sha256:80a78949e339f15f56093123f8d4f0bc8c8e7e6ccb64e2f693dd5e559fa78ff5
#10 CACHED

#16 [builder 4/6] ADD _build/bindep.txt bindep.txt
#16 sha256:7421de9cc67df87835ba73897b9c84f25f1d46e6243fb9b7b6261bf306fc546c
#16 CACHED

#21 [stage-2 6/6] RUN echo This is a post-install command!
#21 sha256:ce77ed9034b995a035dc108fde6aa1f688c3db72ded8c2eee9c6815ebf636f7f
#21 CACHED

#22 exporting to image
#22 sha256:e8c613e07b0b7ff33893b694f7759a10d42e180f2b4dc349fb57dc6b71dcab00
#22 exporting layers done
#22 writing image sha256:0b502056bc7f428e709888d488929d8489bf8ee383cb0e022e4ed126bc8f78bc done
#22 naming to {{ REDACTED }}/ansible-automation-platform/22/ee-vmware-pure:0.1.0 done
#22 DONE 0.0s

Complete! The build context can be found at:
```
> * A simplified project (execution-environment.yml, requirements.txt, etc) that we may use that reproduces the issue.
It's not too long so below is the entire requirements.txt file:
```text
git+https://github.com/vmware/vsphere-automation-sdk-python.git
aiohttp==3.8.3
aiosignal==1.2.0
ansible-builder==1.1.0
ansible-core==2.12.2
async-timeout==4.0.2
attrs==22.1.0
bcrypt==4.0.1
bindep==2.11.0
certifi==2020.12.5
cffi==1.15.1
chardet=<4 >=3.0.2
charset-normalizer==2.1.1
cryptography==36.0.0
decorator==5.1.1
distro==1.8.0
frozenlist==1.3.1
gssapi==1.8.1
idna==2.10
Jinja2==3.1.2
krb5==0.4.0
lxml==4.9.1
MarkupSafe==2.1.1
multidict==6.0.2
ntlm-auth==1.5.0
packaging==21.3
paramiko==2.7.1
Parsley==1.3
pbr==5.10.0
purestorage==1.19.0
py-pure-client==1.20.1
pycparser==2.21
PyJWT<2.0.0 >=1.7.1
PyNaCl==1.5.0
pyOpenSSL==22.1.0
pyparsing==3.0.9
pyspnego==0.6.0
python-dateutil==2.8.1
pyvmomi==7.0.3
pywinrm==0.4.3
PyYAML==6.0
requests==2.25.1
requests-credssp==2.0.0
requests-kerberos==0.14.0
requests-ntlm==1.1.0
requirements-parser==0.5.0
resolvelib==0.5.4
six==1.15.0
types-setuptools==65.4.0.0
typing==3.7.4.3
urllib3==1.26.4
vSphere-Automation-SDK==1.79.0
xmltodict==0.13.0
yarl==1.8.1
```

`execution-environment.yml`
```yaml
---
version: 1

build_arg_defaults:
  EE_BASE_IMAGE: "{{ REDACTED }}/ansible-automation-platform/22/ee-minimal-rhel8:1.0.0-188"
  EE_BUILDER_IMAGE: "{{ REDACTED }}/ansible-automation-platform/22/ansible-builder:latest"

dependencies:
  galaxy: requirements.yml
  python: requirements.txt
  system: bindep.txt

additional_build_steps:
  prepend: |
    RUN python3 -m pip install --upgrade pip
  append:
    - RUN echo This is a test post-install command!
```

In the `bindep.txt` I had to add the following: `krb5-devel [platform:rpm]`
> 
> Thanks.

Hi @Shrews , above is the requested information - I hope this helps!

**Comment by Shrews** [comment] 2022-11-15 19:14
Thanks. Unfortunately, because you're in a cached environment, your output isn't helpful. But fortunately, your example is!

When you use the verbose output I suggested (`-v3`) in a non-cached environment, you'll see a message similar to this buried within it:

```
[2/3] STEP 4/5: RUN ansible-builder introspect --sanitize --user-pip=requirements.txt --user-bindep=bindep.txt --write-bindep=/tmp/src/bindep.txt --write-pip=/tmp/src/requirements.txt
# Sanitized dependencies for /usr/share/ansible/collections
Warning: failed to parse requirements from user, error: Parse error at "'=<4 >=3.'": Expected stringEnd
---
python:
- 'git+https://github.com/vmware/vsphere-automation-sdk-python.git  # from collection
  user'
- 'aiohttp==3.8.3  # from collection user'
- 'aiosignal==1.2.0  # from collection user'
- 'ansible-builder==1.1.0  # from collection user'
- 'ansible-core==2.12.2  # from collection user'
- 'async-timeout==4.0.2  # from collection user'
- 'attrs==22.1.0  # from collection user'
- 'bcrypt==4.0.1  # from collection user'
- 'bindep==2.11.0  # from collection user'
- 'certifi==2020.12.5  # from collection user'
- 'cffi==1.15.1  # from collection user'
system:
- 'krb5-devel [platform:rpm]  # from collection user'
```

The parse error is from `pip` and it has a problem with your requirements.txt file, and stops processing it at that point (it's on our agenda to try to bail out earlier when pip encounters an error). The first error it encounters is with `chardet=<4 >=3.0.2`. That is an improper requirements specifier (see https://pip.pypa.io/en/stable/reference/requirement-specifiers/#requirement-specifiers for more info), so pip stops at that point and never gets to installing the packages below it. You seem to have similar errors within that file. Fix those, and you should be good to go.

**Comment by Shrews** [comment] 2022-11-15 19:18
Closing per above.

**Closed as completed by Shrews** 2022-11-15 19:18 UTC
Labels: needs_info
