### ISSUE TITLE
3.0.0rc1 not installing latest version of pip

### ISSUE THREAD

**Issue by MallocArray** [ansible/ansible-builder#497] opened 2023-04-27 15:48 UTC
During the build process with 3.0.0rc1 I'm seeing messages about pip being version 21.x and 23.x is the latest and it shows a command to upgrade it. 

In the Dockerfile that is generated I see
```
RUN $PYCMD -m ensurepip
```
It looks like adding a flag `--upgrade` to this line would install the latest version, but it isn't user cusomizable
https://docs.python.org/3/library/ensurepip.html

I added this to my .yml file so it upgrades pip at the end of the base
```
  append_base:
    # Upgrade pip to latest version after ansible-builder installs it
    - RUN /usr/bin/python3 -m pip install --upgrade pip
```

Any reason the latest version of pip is not installed by default?

**Comment by nitzmahone** [comment] 2023-04-27 16:30
Yeah, that was on purpose- we're trying to thread the needle between "just works, it's magic" and the needs of disconnected and enterprise use cases where public PyPI / PyPA bootstrap access is a no-go... `ensurepip` is available in the default Python install on most distros and will get us a functional pip without requiring access to an index server, so that's what we do by default. Otherwise we'd have to add and document a bunch more knobs to disable the default behavior, when `ensurepip` is "good enough" for most things in both cases.

We've got a lot more work to do on the disconnected cases, but that's the direction we're trying to work toward, anyway.

Closing as "working as designed".

**Closed as not planned by nitzmahone** 2023-04-27 16:30 UTC
Labels: needs_triage

**Comment by nitzmahone** [comment] 2023-04-27 16:41
... though there is one minor case here that concerns me: we don't have a place to upgrade `pip` before the core/runner installs occur, if that were needed- `prepend_base` is too early (since the Python/pip install occurs after that) and `append_base` is too late.
