### ISSUE TITLE
Support python installs in venv

### ISSUE THREAD

**Issue by kdelee** [ansible/ansible-builder#33] opened 2020-07-02 12:57 UTC
We discussed the possibility that collections will use python dependencies that conflict with the base image's system dependencies. This is one reason why python venvs are used, so users may want to have their python dependencies.

Granted it would then be on the user to properly set `ansible_python_interpreter` in their vars.

Not saying this is top priority but may eventually be a nice feature to install all python deps in a designated venv instead of pip installing to the system

TIL there was a issue to add a env var but didn't make it in back in 2014
https://github.com/ansible/ansible/issues/6345

**Comment by kdelee** [comment] 2021-01-13 16:28
@AlanCoding says this pretty much is not going to happen

**Comment by AlanCoding** [comment] 2021-01-13 16:45
Yes, the main use I see is to aid the migration story from custom venvs -> EEs (heads up, @rebeccahhh is working on that)

The problem is, if we ever do this (allowing the user to keep their `ansible_python_interpreter`), we won't do it in time to help the migration. So... for the consistency and predictability of EEs everywhere, we close this.

**Closed as completed by AlanCoding** 2021-01-13 16:45 UTC
Labels: enhancement
