### ISSUE TITLE
Build fails using ansible/awx-ee:21.12.0 or :latest, with added bindeps

### ISSUE THREAD

**Issue by nroach44** [ansible/ansible-builder#447] opened 2023-02-20 09:03 UTC
Hi!

Using either :latest or ansible/awx-ee:21.12.0, and including (for example) `git-lfs [platform:rpm]` in dependencies: system: causes the build to fail. I'm using `ansible-builder 1.2.0`

```
---
version: 1

build_arg_defaults:
  EE_BASE_IMAGE: 'quay.io/ansible/awx-ee:latest'

dependencies:
  system: reqs-dnf.txt
```
reqs-dnf.txt:
```
git-lfs [platform:rpm]
```

Result:
`ansible-builder build --tag snipped.url/awx-ee:1.1.1-bvt-$(date +%s) -v3`
```
Ansible Builder is building your execution environment image. Tags: snipped.url/awx-ee:1.1.1-bvt-1676881956
File context/_build/bindep.txt will be created.
Rewriting Containerfile to capture collection requirements
Running command:
  podman build -f context/Containerfile -t snipped.url/awx-ee:1.1.1-bvt-1676881956 context
STEP 1: FROM quay.io/ansible/awx-ee:latest AS galaxy
...
STEP 9: RUN ansible-builder introspect --sanitize --user-bindep=bindep.txt --write-bindep=/tmp/src/bindep.txt --write-pip=/tmp/src/requirements.txt
# Sanitized dependencies for /usr/share/ansible/collections
---
python: []
system:
- 'git-lfs [platform:rpm]  # from collection user'

Creating parent directory for /tmp/src/bindep.txt
--> 7789160bf3f
STEP 10: RUN assemble
++ source /etc/os-release
+++ NAME='CentOS Stream'
+++ VERSION=8
...
Installed:
  git-lfs-3.2.0-2.el8.x86_64

Complete!
...
STEP 14: RUN /output/install-from-bindep && rm -rf /output/wheels
+ PKGMGR=
+ PKGMGR_OPTS=
+ '[' -z ']'
+ PKGMGR=/usr/bin/dnf
+ '[' -f /usr/bin/microdnf ']'
+ /usr/bin/dnf update -y
...
  python3-systemd-234-18.el9.x86_64

Complete!
+ '[' -f /output/bindep/run.txt ']'
++ cat /output/bindep/run.txt
+ PACKAGES='git
python38-wheel
git-lfs'
+ '[' '!' -z 'git
python38-wheel
git-lfs' ']'
+ /usr/bin/dnf install -y git python38-wheel git-lfs
Last metadata expiration check: 0:00:07 ago on Mon Feb 20 08:38:45 2023.
No match for argument: python38-wheel
Package git-lfs-3.2.0-1.el9.x86_64 is already installed.
Error: Unable to find a match: python38-wheel
Error: error building at STEP "RUN /output/install-from-bindep && rm -rf /output/wheels": error while running runtime: exit status 1

An error occured (rc=125), see output line(s) above for details.
```

Setting the tag on `EE_BASE_IMAGE` to `21.11.0` or removing the bindep allows the build to go through.

I'm pretty new to containers & the internals of AWX, so I'm happy to take this to the awe-ee project and log it over there, if this is something that needs to be fixed there. 

From what I can tell, it looks like ansible-builder is hard-coding the package in https://github.com/ansible/ansible-builder/blob/devel/bindep.txt#L5 which might not be right for the newer awx-ee image.

**Comment by maximerobine** [comment] 2023-03-06 18:31
Hello, i had the same problem. I think it's due to the fact that awx-ee:latest is based on Centos Stream 9. I cannot find any information about when ansible-builder will be fixed, but for now you cannot build EE from Centos Stream 9 images using ansible-builder.
I build my EEs from the [awx-ee repo](https://github.com/ansible/awx-ee). I add my python modules, ansible collections and system packages in the already existing file in [_build folder](https://github.com/ansible/awx-ee/tree/devel/_build) and add some post building steps at the end of the [Dockerfile](https://github.com/ansible/awx-ee/blob/devel/Containerfile). Then I execute docker build to build the image.
I don't know if it's the correct/intend way of building EE with the latest version of Ansible, but i did not find anything else for now.
I hope ansible-builder will be fixed soon.

**Comment by Shrews** [comment] 2023-03-07 15:23
FWIW, using the example execution environment you supplied (and specifying the `awx-ee:21.12.0` explicitly), the build works for me. Unsure if there have been changes to the awx-ee image or not (that is not under our control). Are you seeing the same error now?

We are in the process of reworking builder to eliminate a lot of headaches (builder image dependency, unable to specify python or ansible versions, etc). We expect this work to be finished this spring.

**Comment by nroach44** [comment] 2023-03-09 04:52
@Shrews 

I wiped my caches:

```
buildah rm --all; rm -rfv context; podman image rm --all
```

`execution-environment.yml`:

```
---
version: 1

build_arg_defaults:
  EE_BASE_IMAGE: 'quay.io/ansible/awx-ee:21.12.0'

dependencies:
  system: reqs-dnf.txt
```

`reqs-dnf.txt`:

```
git-lfs [platform:rpm]
```

```
nroach:~/working/awx-ee$ pip install --upgrade ansible-builder
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: ansible-builder in /home/nroach/.local/lib/python3.9/site-packages (1.2.0)
...
```

`ansible-builder build --tag registry/stuff/awx-ee:version-bvt-$(date +%s) -v3`
```
STEP 14: RUN /output/install-from-bindep && rm -rf /output/wheels
+ PKGMGR=
+ PKGMGR_OPTS=
+ '[' -z ']'
+ PKGMGR=/usr/bin/dnf
+ '[' -f /usr/bin/microdnf ']'
+ /usr/bin/dnf update -y
--- snip ---
Installed:
  dbus-libs-1:1.12.20-7.el9.x86_64
  dnf-plugins-core-4.3.0-4.el9.noarch
  glibc-langpack-en-2.34-60.el9.x86_64
  python3-dateutil-1:2.8.1-6.el9.noarch
  python3-dbus-1.2.18-2.el9.x86_64
  python3-dnf-plugins-core-4.3.0-4.el9.noarch
  python3-six-1.15.0-9.el9.noarch
  python3-systemd-234-18.el9.x86_64

Complete!
+ '[' -f /output/bindep/run.txt ']'
++ cat /output/bindep/run.txt
+ PACKAGES='git
python38-wheel
git-lfs'
+ '[' '!' -z 'git
python38-wheel
git-lfs' ']'
+ /usr/bin/dnf install -y git python38-wheel git-lfs
Last metadata expiration check: 0:00:17 ago on Thu Mar  9 02:28:23 2023.
No match for argument: python38-wheel
Package git-lfs-3.2.0-1.el9.x86_64 is already installed.
Error: Unable to find a match: python38-wheel
Error: error building at STEP "RUN /output/install-from-bindep && rm -rf /output/wheels": error while running runtime: exit status 1

An error occured (rc=125), see output line(s) above for details.
```

The same happens with `quay.io/ansible/awx-ee:21.13.0` and `:latest`

**Comment by nroach44** [comment] 2023-03-09 04:55
I'm happy to upload the full log (with sensitive bits removed) if you'd like?

Otherwise I'm not sure what I'd be doing differently to you.

**Comment by nroach44** [comment] 2023-03-13 07:02
As a temporary fix, editing this repo's bindep.txt to remove the python38-devel package, and building it, and using the updated builder container, does seem to work:

`nano bindep.txt`
```
# This is a cross-platform list tracking distribution packages needed by tests;
# see https://docs.openstack.org/infra/bindep/ for additional information.

git
```

`podman build .`
```
STEP 10: COMMIT
--> 6fb3f0176b3
6fb3f0176b303538e7980e11e187713f664aff8ee53ca31ac1c6ca3c453ed913
```

`cd ../ee`
`execution-environment.yml`
```
---
version: 1

build_arg_defaults:
  EE_BASE_IMAGE: 'quay.io/ansible/awx-ee:latest'
  EE_BUILDER_IMAGE: '6fb3f0176b303538e7980e11e187713f664aff8ee53ca31ac1c6ca3c453ed913'

dependencies:
  system: reqs-dnf.txt
  ```

`ansible-builder build --tag ... -v3`
```
STEP 7: FROM 6fb3f0176b303538e7980e11e187713f664aff8ee53ca31ac1c6ca3c453ed913 AS builder
STEP 8: ADD _build/bindep.txt bindep.txt
--> 3d9a5541249
...
STEP 15: LABEL ansible-execution-environment=true
STEP 16: COMMIT ...
--> 2af8798c37c
```

**Comment by Xiol** [comment] 2023-04-11 13:37
I had a similar issue with 21.14.0.

```
...snip...
+ /usr/bin/dnf install -y cryptsetup openssh-clients openssl python3-cryptography python3-pyOpenSSL python3-rpm python38-cryptography python38-pytz python38-pyyaml python38-requests python39-cffi python39-cryptography python39-lxml python39-pycparser python39-six qemu-img
Last metadata expiration check: 0:00:08 ago on Tue Apr 11 12:24:32 2023.
Package openssh-clients-8.7p1-28.el9.x86_64 is already installed.
Package openssl-1:3.0.7-6.el9.x86_64 is already installed.
Package python3-rpm-4.16.1.3-22.el9.x86_64 is already installed.
No match for argument: python38-cryptography
No match for argument: python38-pytz
No match for argument: python38-pyyaml
No match for argument: python38-requests
No match for argument: python39-cffi
No match for argument: python39-cryptography
No match for argument: python39-lxml
No match for argument: python39-pycparser
No match for argument: python39-six
Package qemu-img-17:7.2.0-14.el9.x86_64 is already installed.
Error: Unable to find a match: python38-cryptography python38-pytz python38-pyyaml python38-requests python39-cffi python39-cryptography python39-lxml python39-pycparser python39-six
The command '/bin/sh -c /output/install-from-bindep && rm -rf /output/wheels' returned a non-zero code: 1
An error occured (rc=1), see output line(s) above for details.
```

I had the same error with 21.12.0.

Reverting back to 21.11.0 resolved this and allowed the image build to complete.

### Configuration

execution-environment.yml
```yaml
---
version: 1

build_arg_defaults:
  EE_BASE_IMAGE: 'quay.io/ansible/awx-ee:21.14.0'

dependencies:
  galaxy: requirements.yml
  python: requirements.txt

additional_build_steps:
  prepend: |
    RUN update-crypto-policies --set DEFAULT:SHA1
```

requirements.txt
```
docker~=6.0.0
ansible-runner~=2.3
```

requirements.yml
```yaml
---

collections:
  - ansible.netcommon
  - ansible.posix
  - ansible.utils
  - ansible.windows
  - awx.awx
  - cloud.common
  - community.crypto
  - community.dns
  - community.docker
  - community.general
  - community.hashi_vault
  - community.kubernetes
  - community.mysql
  - community.network
  - community.postgresql
  - community.rabbitmq
  - community.windows
  - community.vmware
  - community.general
  - kubernetes.core
  - openstack.cloud
```

**Comment by Shrews** [comment] 2023-04-20 17:38
@nroach44 Sorry, just getting back around to looking at this again.

I'm afraid I still cannot reproduce the error you are seeing using the `execution-environment.yml` file and `reqs-dnf.txt` from your original report. Are there any other steps or files you might not have reported, no matter how inconsequential, that could help us out here? If not, I can look through the full redacted logs if you can supply that.

The steps I took were:

```
$ buildah rm --all && podman image rm --all
$ python3 -m venv venv
$ source venv/bin/activate
$ pip install ansible-builder==1.2.0
$ ansible-builder build --tag issue447:test -v3
```

FWIW, my version of podman is `3.4.4`.

Removing the python38 requirement from builder's repo is a red herring, I believe. If I'm not mistaken, that file is only used when building the `ansible-builder` image for quay.io and shouldn't be impacting any new build. If anything, removing that and building a new image is likely just hiding the real problem.

I'm not sure what is happening in your situation, but this doesn't feel like a builder issue. I suspect either some missing piece particular to your environment, or possibly with the one of the base images (I myself have had mysterious issues occur with centos stream9, the base image for that awx-ee image, that seem to come and go).

**Comment by Shrews** [comment] 2023-06-27 15:51
Closing due to inactivity.

**Closed as completed by Shrews** 2023-06-27 15:51 UTC
Labels: needs_info
